### ISSUE TITLE
InvalidContentEntryDataError: Reference to users invalid - Entry does not exist

### ISSUE THREAD

**Issue by EBFcode** [delucis/dewp#5]
I encountered an issue while running `pnpm dev` with Astro v5.0.0-beta.5 in the second time running (without change anything in the code) . The process fails with an `InvalidContentEntryDataError`. The error message states that there is an issue with the content schema, specifically that there is a reference to a non-existent user entry (Entry 1819835).

**Steps to Reproduce:**
1. Run the command `pnpm dev` in the project directory.
2. Observe the error outputting `InvalidContentEntryDataError`.

**Actual Behavior:**
The command fails with the following error message:
pages → 15740 data does not match collection schema.
author: Reference to users invalid. Entry 1819835 does not exist.
**Additional Context:**
- Local development server URL: http://localhost:4321/
- Using Astro v5.0.0-beta.5
- More information on content schemas: https://docs.astro.build/en/guides/content-collections/
- Error reference: https://docs.astro.build/en/reference/errors/invalid-content-entry-data-error/

Please let me know if further information is needed to resolve this issue. Thank you.

**Comment by delucis** [comment]
Thanks for the issue @EBFcode!

Does deleting the `.astro/` directory in the project root and re-running `pnpm dev` work?

**Comment by GoyisDev** [comment]
Yeah! It works. 

I did this: 

Started a new project from scratch `pnpm create astro --template delucis/dewp/examples/blog-starter`
-
`pnpm dev`
##Terminal:
`
> testing-wp@0.0.1 dev /Users//[Dev-Astro]/Test/testing-wp
> astro dev

19:09:27 [types] Generated 1ms

 astro  v5.0.0-beta.5 ready in 125 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

▶ This is a  beta  prerelease build!
  Report issues here: https://astro.build/issues

19:09:27 [content] Syncing content
19:09:27 [content] Content config changed
19:09:27 [content] Astro version changed
19:09:27 [content] Clearing content store
The collection "site-settings" does not exist. Please ensure it is defined in your content config.
19:09:46 [ERROR] Cannot read properties of undefined (reading 'data')
  Stack trace:
    at /Users//[Dev-Astro]/Test/testing-wp/node_modules/.pnpm/dewp@0.0.4_astro@5.0.0-beta.5/node_modules/dewp/content-utils.ts:9:15
    [...] See full stack trace in the browser, or rerun with --verbose.
19:09:49 [content] Synced content
19:09:49 watching for file changes...
19:09:52 [200] / 2696ms
19:09:52 [200] / 2321ms
19:09:58 [200] /blog 34ms
19:10:03 [200] /blog/wordpress-community-creates-1000-block-themes-in-1000-days/ 10ms
19:10:05 [200] /blog 38ms
19:10:07 [200] /blog/protect-private-conversations/ 15ms
19:10:08 [200] /blog 38ms
19:10:10 [200] / 12ms
19:10:11 [200] /blog 48ms
19:10:12 [200] / 15ms
^C%                                                                                                  `
----
## Then I stop the run and started again: 

> testing-wp@0.0.1 dev /Users/j/[Dev-Astro]/Test/testing-wp
> astro dev

19:10:20 [types] Generated 0ms

 astro  v5.0.0-beta.5 ready in 96 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

▶ This is a  beta  prerelease build!
  Report issues here: https://astro.build/issues

19:10:21 [content] Syncing content
19:10:24 [200] / 11ms
[InvalidContentEntryDataError] pages → 15740 data does not match collection schema.
author: Reference to users invalid. Entry 1819835 does not exist.
  Hint:
    See https://docs.astro.build/en/guides/content-collections/ for more information on content schemas.
  Error reference:
    https://docs.astro.build/en/reference/errors/invalid-content-entry-data-error/
  Stack trace:
    at getEntryDataAndImages (file:///Users/j/[Dev-Astro]/Test/testing-wp/node_modules/.pnpm/astro@5.0.0-beta.5_typescript@5.6.3/node_modules/astro/dist/content/utils.js:158:26)
    at async Object.load (/Users/j/[Dev-Astro]/Test/testing-wp/node_modules/.pnpm/dewp@0.0.4_astro@5.0.0-beta.5/node_modules/dewp/loaders.ts:51:22)
    at async #doSync (file:///Users/jh/[Dev-Astro]/Test/testing-wp/node_modules/.pnpm/astro@5.0.0-beta.5_typescript@5.6.3/node_modules/astro/dist/content/content-layer.js:131:5)
 ELIFECYCLE  Command failed with exit code 1.
 
 
 ### I deleted the `.astro/` and started again and it works (again) but if I stop and start again it is broken again.

**Comment by sgalcheung** [comment]
I also noticed the method of `wpCollections>makeLoader>fetchAll` call many times when starting up this project.

**Comment by delucis** [comment]
> I deleted the `.astro/` and started again and it works (again) but if I stop and start again it is broken again.

Thanks for confirming @EBFcode. It seems that Astro’s caching logic is not working correctly ending up with bad state between runs. We’ll probably need to open an issue upstream.
